// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPaZgU5A4ic10bEhY5vTzTeBRI5ddfe4',
    appId: '1:267363955785:web:b73cf4d7b2e0a9e1967b98',
    messagingSenderId: '267363955785',
    projectId: 'budge-tracker-app',
    authDomain: 'budge-tracker-app.firebaseapp.com',
    storageBucket: 'budge-tracker-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFu3KY37-970Q-PD3HR6mSIeczDOhYiNk',
    appId: '1:267363955785:android:036824ecb31f537e967b98',
    messagingSenderId: '267363955785',
    projectId: 'budge-tracker-app',
    storageBucket: 'budge-tracker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyt920U0LCjo0tBOsenVZZoUQjKRJJ2Q',
    appId: '1:267363955785:ios:0958386d4f405f48967b98',
    messagingSenderId: '267363955785',
    projectId: 'budge-tracker-app',
    storageBucket: 'budge-tracker-app.appspot.com',
    iosBundleId: 'com.example.budgeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyt920U0LCjo0tBOsenVZZoUQjKRJJ2Q',
    appId: '1:267363955785:ios:0958386d4f405f48967b98',
    messagingSenderId: '267363955785',
    projectId: 'budge-tracker-app',
    storageBucket: 'budge-tracker-app.appspot.com',
    iosBundleId: 'com.example.budgeTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfPaZgU5A4ic10bEhY5vTzTeBRI5ddfe4',
    appId: '1:267363955785:web:d1ca363b280746e8967b98',
    messagingSenderId: '267363955785',
    projectId: 'budge-tracker-app',
    authDomain: 'budge-tracker-app.firebaseapp.com',
    storageBucket: 'budge-tracker-app.appspot.com',
  );
}
